window_name: tilemap-editor
screen:
    fullscreen: ON
    width: 1600
    height: 900
asset_path: resources/assets
tile_filenames:
  - tiles.png
  - buildings.png
  - props-01.png
tile_size_px: 16
main_grid:
  count_x: 100
  count_y: 100
  initial_scale: 3

texture_grid:
  initial_scale: 3
  margin: 1

tile_bank:
  position_x: 0.03
  position_y: 0.13
  count_x: 5
  count_y: 13
  gap: 10
  scale: 3

interface:
  main_area:
    layer: 4
    type: box
    position_x: 0
    position_y: 0
    width: 1
    height: 1
    color:
      r: 0
      g: 0
      b: 0
      a: 0
  texture_area:
    layer: 2
    type: box
    position_x: 0.025
    position_y: 0.125
    width: 0.29
    height: 0.49
    color:
      r: 0
      g: 0
      b: 0
      a: 0
  reload_button:
    layer: 1
    type: textbox
    position_x: 0.45 
    position_y: 0.05
    width: 0.1
    height: 0.05
    text: "RELOAD_UI"
    text_margin: 0.2
    color:
      r: 0
      g: 121
      b: 241
      a: 150
  tile_bank:
    layer: 3
    type: box
    position_x: 0.02 
    position_y: 0.05
    width: 0.3
    height: 0.60
    color:
      r: 200
      g: 200
      b: 200
      a: 255
  tile_bank_arrow_left:
    layer: 1
    type: triangle
    p1x: 0.025
    p1y: 0.055
    p2x: 0.04
    p2y: 0.07
    p3x: 0.04
    p3y: 0.04
    color:
      r: 0
      g: 121
      b: 241
      a: 255
  tile_bank_arrow_right:
    layer: 1
    type: triangle
    p1x: 0.30
    p1y: 0.07
    p2x: 0.315
    p2y: 0.055 
    p3x: 0.30
    p3y: 0.04
    color:
      r: 0
      g: 121
      b: 241
      a: 255
  tilemap_filename:
    layer: 1
    type: text
    position_x: 0.05
    position_y: 0.08
    font_size: 20
    text: "No texture files found"
    color:
      r: 0
      g: 0
      b: 0
      a: 255


